name: Prod Docs Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: v16
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: export NITRO_PRESET=vercel && vercel build --prod -d --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy  --prebuilt --prod -d --token=${{ secrets.VERCEL_TOKEN }}
